// Code generated by a fixture stand-in. DO NOT EDIT.

package nilDeclCompleteness

// GeneratedLookup would report every position under the rule, and
// stays silent because the file carries the generated-code header: the
// contract belongs on whatever the generator reads, not here.
func GeneratedLookup(key *string) *Record { return &Record{Name: *key} }
