// This file pins the negative side of the generated-file exemption.
// The prose below mentions both halves of the header sentence without
// being the header, so the rule must still reach the declaration: this
// file is not
// Code generated by any tool, so DO NOT EDIT. does not apply to it.
//
// The canonical form lives in generated.go, whose declaration stays
// silent; together the two files pin where the exemption starts and
// stops.

package nilDeclCompleteness

func proseHeaderIsNotGenerated(key *string) *Record { // want `vow\[nil-decl\]: vow:nil leaves parameter key, return 1 without a nullness decl`
	return &Record{Name: *key}
}
