package analysis

import (
	"go/parser"
	"go/token"
	"testing"

	"github.com/knowledge-work/go-vow/internal/assert"
	"github.com/knowledge-work/go-vow/internal/tabletest"
)

// TestFileIsGeneratedRequiresCanonicalHeader pins the boundary of the
// generated-file exemption. The exemption is silent — an exempted file
// reports nothing — so a match looser than the canonical header would
// drop a file out of the completeness rule with no signal. The prose
// case is the one that matters: mentioning both halves of the sentence
// in running text must not exempt the file.
func TestFileIsGeneratedRequiresCanonicalHeader(t *testing.T) {
	type generatedCase struct {
		src  string
		want bool
	}

	tabletest.Run(t, map[string]generatedCase{
		"canonical header":             {"// Code generated by mockgen. DO NOT EDIT.\n\npackage p\n", true},
		"prose mentioning both halves": {"// This file is not\n// Code generated by any tool, so DO NOT EDIT. does not apply.\n\npackage p\n", false},
		"block comment":                {"/* Code generated by x. DO NOT EDIT. */\n\npackage p\n", false},
		"missing trailing period":      {"// Code generated by x. DO NOT EDIT\n\npackage p\n", false},
		"after the package clause":     {"package p\n\n// Code generated by x. DO NOT EDIT.\n", false},
		"ordinary doc comment":         {"// Package p does things.\n\npackage p\n", false},
	}, func(t *testing.T, c generatedCase) {
		file, err := parser.ParseFile(token.NewFileSet(), "p.go", c.src, parser.ParseComments)
		assert.MustNoError(t, "parse fixture source", err)
		assert.Equal(t, "fileIsGenerated()", fileIsGenerated(file), c.want)
	})
}
